export const AUTH_USER = 'AUTH_USER';
export const INVALIDATE_USER = 'INVALIDATE_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const INIT_AUTH_USER = 'INIT_AUTH_USER';
export const SET_MENU_STATE = 'SET_MENU_STATE';


export const GET_SERVICES = 'GET_SERVICES';
export const POST_SERVICE = 'POST_SERVICE';
export const GET_SERVICE = 'GET_SERVICE';
export const PUT_SERVICE = 'PUT_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const LOAD_SERVICES = 'LOAD_SERVICES';


export const GET_REGEXS = 'GET_REGEXS';
export const POST_REGEX = 'POST_REGEX';
export const GET_REGEX = 'GET_REGEX';
export const PUT_REGEX = 'PUT_REGEX';
export const DELETE_REGEX = 'DELETE_REGEX';
export const LOAD_REGEXS = 'LOAD_REGEXS';


export const SELECT_SERVICE_REGEX = 'SELECT_SERVICE_REGEX';
export const POST_SERVICE_REGEX = 'POST_SERVICE_REGEX';
export const PUT_SERVICE_REGEX = 'PUT_SERVICE_REGEX';
export const DELETE_SERVICE_REGEX = 'DELETE_SERVICE_REGEX';

export const SELECT_SERVICE_SCHEMA = 'SELECT_SERVICE_SCHEMA';
export const POST_SERVICE_SCHEMA = 'POST_SERVICE_SCHEMA';
export const PUT_SERVICE_SCHEMA = 'PUT_SERVICE_SCHEMA';
export const DELETE_SERVICE_SCHEMA = 'DELETE_SERVICE_SCHEMA';

export const SELECT_SERVICE_DEPENDENCY = 'SELECT_SERVICE_DEPENDENCY';
export const POST_SERVICE_DEPENDENCY = 'POST_SERVICE_DEPENDENCY';
export const PUT_SERVICE_DEPENDENCY = 'PUT_SERVICE_DEPENDENCY';
export const DELETE_SERVICE_DEPENDENCY = 'DELETE_SERVICE_DEPENDENCY';

export const GET_DEPENDENCIES = 'GET_DEPENDENCIES';
export const GET_DEPENDENCY = 'GET_DEPENDENCY';
export const POST_DEPENDENCY = 'POST_DEPENDENCY';
export const PUT_DEPENDENCY = 'PUT_DEPENDENCY';
export const DELETE_DEPENDENCY = 'DELETE_DEPENDENCY';
export const LOAD_DEPENDENCIES = 'LOAD_DEPENDENCIES';

export const GET_SYSTEM = 'GET_SYSTEM';
export const RELOAD_LDP = 'RELOAD_LDP';
export const IMPORT_LDP = 'IMPORT_LDP';
export const CLEAR_MSG = 'CLEAR_MSG';
export const CLEAR_SYSTEM_ERROR_MSG = 'CLEAR_SYSTEM_ERROR_MSG';
export const SORT_SERVICE_TABLE = 'SORT_SERVICE_TABLE';
export const SORT_REGEX_TABLE = 'SORT_REGEX_TABLE';
export const SORT_DEPENDENCY_TABLE = 'SORT_DEPENDENCY_TABLE';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const POST_USER = 'POST_USER';
export const PUT_USER = 'PUT_USER';
export const DELETE_USER = 'DELETE_USER';
export const LOAD_USERS = 'LOAD_USERS';